version: "3.9"

services:
  app:
    build: .
    image: strideon-backend:latest
    ports:
      - "8000:8000"
    environment:
      # Provide your own values via an .env file or environment
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      DEBUG_USER_ID: ${DEBUG_USER_ID}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/0}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-"*"}
      VERY_RPC_URL: ${VERY_RPC_URL:-http://127.0.0.1:8545}
      VERY_CHAIN_ID: ${VERY_CHAIN_ID:-1337}
      VERY_CONTRACT_ADDR: ${VERY_CONTRACT_ADDR:-0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: strideon-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
