platform :ios, '16.0'

target 'StrideOn' do
  use_frameworks!

  pod 'AppAuth'
  pod 'WepinWidget', :path => './wepin-ios-sdk-widget-v1'
  pod 'WepinCommon', :path => './wepin-ios-sdk-internal-v1/packages/WepinCommon'
  pod 'WepinCore', :path => './wepin-ios-sdk-internal-v1/packages/WepinCore'
  pod 'WepinModal', :path => './wepin-ios-sdk-internal-v1/packages/WepinModal'
  
  # This block fixes build errors for some crypto libraries Wepin uses
  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
          config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
        end
      end
    end
    
    # Fix BCrypt's import bcryptc issue
    bcrypt_file = File.join(installer.sandbox.root, 'BCrypt', 'BCrypt', 'Classes', 'PerfectBCrypt', 'PerfectBCrypt.swift')
    if File.exist?(bcrypt_file)
      content = File.read(bcrypt_file)
      new_content = content.gsub(/^import bcryptc$/, '// import bcryptc // Patched by Podfile')
      File.write(bcrypt_file, new_content)
      puts "[Podfile] Patched BCrypt to remove 'import bcryptc'"
    end
  end
end